services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: minisiem
      POSTGRES_PASSWORD: minisiem
      POSTGRES_DB: minisiem
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - osdata:/usr/share/opensearch/data

  api:
    build: ./services/api
    environment:
      REDIS_URL: redis://redis:6379/0
      OPENSEARCH_URL: http://opensearch:9200
      DATABASE_URL: postgresql+psycopg://minisiem:minisiem@postgres:5432/minisiem
    ports: ["8000:8000"]
    depends_on: [redis, postgres, opensearch]

  ingestor:
    build: ./services/ingestor
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on: [redis]

  normalizer:
    build: ./services/normalizer
    environment:
      REDIS_URL: redis://redis:6379/0
      OPENSEARCH_URL: http://opensearch:9200
    depends_on: [redis, opensearch]

  detector:
    build: ./services/detector
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg://minisiem:minisiem@postgres:5432/minisiem
    depends_on: [redis, postgres]

volumes:
  pgdata:
  osdata: